name: CI - Build and Test in Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-maven-app .

      - name: Run tests inside container
        id: run-tests
        run: docker run --name test-run my-maven-app

      - name: Copy Cucumber report
        if: always()
        run: |
          docker cp test-run:/app/target/cucumber-report.html ./cucumber-report.html || echo "No report found"
          docker rm test-run

      - name: List target directory
        if: always()
        run: ls -R target || true

      - name: Upload Cucumber Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: cucumber-report.html

      - name: Set test result message
        if: always()
        id: set-message
        run: |
          REPORT_LINK="https://jaabless.github.io/SwagLabs_Cucumber/cucumber-report.html"
          if [ "${{ steps.run-tests.outcome }}" == "success" ]; then
            MSG="✅ All tests passed successfully for *${GITHUB_REPOSITORY}* on branch *${GITHUB_REF}*"
          else
            MSG="❌ Some tests failed in *${GITHUB_REPOSITORY}* on branch *${GITHUB_REF}*"
          fi
          echo "message=${MSG} | 📊 <${REPORT_LINK}|View Full Report>" >> $GITHUB_OUTPUT

  deploy-cucumber-report:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Cucumber reports
        uses: actions/download-artifact@v4
        with:
          name: cucumber-report
          path: cucumber-report   # this will be a directory

      - name: Deploy report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: cucumber-report
          publish_branch: gh-pages

  notify:
    needs: [ build-and-test, deploy-cucumber-report ]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          text: ${{ needs.build-and-test.outputs.message }}
          fields: repo,commit,author,ref
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.NEWSLETTER_CHANNEL }}
